web:
  restart: always
  build: ./web
  ports:
    - "80:80"
  links:
    - postgres:postgres
    - redis:redis
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :80 app:app

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"

redis:
  restart: always
  image: redis:latest
  volumes:
    - /var/lib/redis
  ports:
    - "6379:6379"
