"""empty message

Revision ID: 28fa3b811a15
Revises: 01d06e2e7536
Create Date: 2016-03-13 23:37:08.936838

"""

# revision identifiers, used by Alembic.
revision = '28fa3b811a15'
down_revision = '01d06e2e7536'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('dadjoke', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'dadjoke')
    ### end Alembic commands ###
